@startsalt eliminarProyecto-wireframe
{
    ====
    <b>GIPF - ELIMINAR PROYECTO</b>
    ====
    {
        <b>Proyecto seleccionado</b>
        --
        {
            <b>Código:</b> PRY-SAN-CREADO-01
            <b>Título:</b> Proyecto pendiente de definición
            <b>Estado:</b> Creado
        }
        --
        <b>Comprobación de dependencias</b>
        --
        {
            Sin entregables, recompensas ni responsabilidades vinculadas.
        }
        --
        <b>Esta acción no se puede deshacer.</b>
        --
        {[Eliminar proyecto] | [Cancelar]}
    }
}
@endsalt
