@startuml eliminarPublicacion-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":PUBLICACION_ABIERTA" as EstadoEntrada
package eliminarPublicacion as "eliminarPublicacion()" {
    rectangle #629EF9 EliminarPublicacionView
    rectangle #b5bd68 PublicacionController
    rectangle #F2AC4E PublicacionRepository
    rectangle #F2AC4E Publicacion
}

rectangle #CDEBA5 ":PUBLICACIONES_ABIERTAS" as EstadoSalida
rectangle #CDEBA5 ":Collaboration AbrirPublicaciones" as AbrirPublicaciones

EstadoEntrada -r-> EliminarPublicacionView: eliminarPublicacion()

EliminarPublicacionView -d-> PublicacionController: eliminarPublicacion(id)
EliminarPublicacionView --> PublicacionController: validarEliminacion(id)
PublicacionController --> PublicacionRepository: obtenerPorId(id)
PublicacionController --> PublicacionRepository: eliminar(id)
PublicacionRepository -- Publicacion
EliminarPublicacionView ..> EstadoSalida: continuarNavegacion()
EliminarPublicacionView ..> AbrirPublicaciones: abrirPublicaciones()

@enduml
