@startuml abrirRecompensa-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":RECOMPENSAS_ABIERTAS" as EstadoEntrada
package abrirRecompensa as "abrirRecompensa()" {
    rectangle #629EF9 DetalleRecompensaView
    rectangle #b5bd68 RecompensaController
    rectangle #F2AC4E RecompensaRepository
    rectangle #F2AC4E Recompensa
}

rectangle #CDEBA5 ":RECOMPENSA_ABIERTA" as EstadoSalida
rectangle #CDEBA5 ":Collaboration AbrirRecompensas" as AbrirRecompensas

EstadoEntrada -r-> DetalleRecompensaView: abrirRecompensa()

DetalleRecompensaView -d-> RecompensaController: obtenerRecompensa(id)
DetalleRecompensaView --> RecompensaController: prepararAccionesDisponibles(investigador)
RecompensaController --> RecompensaRepository: obtenerPorId(id)
RecompensaController --> RecompensaRepository: verificarPermisos(actor)
RecompensaRepository -- Recompensa
DetalleRecompensaView ..> EstadoSalida: continuarNavegacion()
DetalleRecompensaView ..> AbrirRecompensas: abrirRecompensas()

@enduml
