@startuml eliminarEntregable-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":ENTREGABLE_ABIERTO" as EstadoEntrada
package eliminarEntregable as "eliminarEntregable()" {
    rectangle #629EF9 EliminarEntregableView
    rectangle #b5bd68 EntregableController
    rectangle #F2AC4E EntregableRepository
    rectangle #F2AC4E Entregable
}

rectangle #CDEBA5 ":ENTREGABLES_ABIERTOS" as EstadoSalida
rectangle #CDEBA5 ":Collaboration AbrirEntregables" as AbrirEntregables
rectangle #CDEBA5 ":Collaboration AbrirEntregable" as AbrirEntregable

EstadoEntrada -r-> EliminarEntregableView: eliminarEntregable()

EliminarEntregableView -d-> EntregableController: eliminarEntregable(id)
EliminarEntregableView --> EntregableController: validarEliminacion(id)
EntregableController --> EntregableRepository: obtenerPorId(id)
EntregableController --> EntregableRepository: eliminar(id)
EntregableRepository -- Entregable
EliminarEntregableView ..> EstadoSalida: continuarNavegacion()
EliminarEntregableView ..> AbrirEntregables: abrirEntregables()
EliminarEntregableView ..> AbrirEntregable: abrirEntregable()

@enduml
