@startuml eliminarPublicacion

skinparam linetype polyline

state in2 as "PUBLICACION_ABIERTA"
in2 -[#green]-> eliminarPublicacion
note on link
eliminarPublicacion()
end note

state eliminarPublicacion as "eliminarPublicacion()" {

    state " " as ConfirmandoRetirada
    state " " as PublicacionRetirada

    [*] -[#green]-> ConfirmandoRetirada
    note on link
    <b>Coordinador</b> solicita retirar publicación
    end note

    ConfirmandoRetirada -[#green]-> PublicacionRetirada
    note on link
    <b>Sistema</b> presenta confirmación de retirada
    <b>Coordinador</b> solicita confirmar retirada
    <b>Sistema</b> presenta la retirada de la publicación
    end note

    ConfirmandoRetirada -[#red]-> [*]
    note on link
    <b>Coordinador</b> solicita cancelar la operación
    end note

    PublicacionRetirada -[#green]-> [*]
    note on link
    <b>Sistema</b> presenta confirmación de retirada
    end note
}



eliminarPublicacion -[#green]-> PUBLICACIONES_ABIERTAS
note on link
abrirPublicaciones()
end note

@enduml
