@startuml abrirRecompensas-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":RECOMPENSA_ABIERTA" as EstadoEntrada
package abrirRecompensas as "abrirRecompensas()" {
    rectangle #629EF9 ListarRecompensasView
    rectangle #b5bd68 RecompensaController
    rectangle #F2AC4E RecompensaRepository
    rectangle #F2AC4E Recompensa
}

rectangle #CDEBA5 ":RECOMPENSAS_ABIERTAS" as EstadoSalida
rectangle #CDEBA5 ":Collaboration AbrirRecompensa" as AbrirRecompensa
rectangle #CDEBA5 ":Collaboration AbrirPanelPrincipal" as AbrirPanelPrincipal

EstadoEntrada -r-> ListarRecompensasView: abrirRecompensas()

ListarRecompensasView -d-> RecompensaController: listarRecompensas()
ListarRecompensasView --> RecompensaController: filtrarRecompensas(criterio)
RecompensaController --> RecompensaRepository: obtenerTodos()
RecompensaController --> RecompensaRepository: buscarPorCriterio(criterio)
RecompensaRepository -- Recompensa
ListarRecompensasView ..> EstadoSalida: continuarNavegacion()
ListarRecompensasView ..> AbrirRecompensa: abrirRecompensa()
ListarRecompensasView ..> AbrirPanelPrincipal: abrirPanelPrincipal()

@enduml
