@startuml eliminarMiPublicacion-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":MI_PUBLICACION_ABIERTA" as EstadoEntrada
package eliminarMiPublicacion as "eliminarMiPublicacion()" {
    rectangle #629EF9 EliminarPublicacionView
    rectangle #b5bd68 PublicacionController
    rectangle #F2AC4E PublicacionRepository
    rectangle #F2AC4E Publicacion
}

rectangle #CDEBA5 ":MIS_PUBLICACIONES_ABIERTAS" as EstadoSalidaExitosa
rectangle #CDEBA5 ":MI_PUBLICACION_ABIERTA" as EstadoSalidaCancelada


EstadoEntrada -r-> EliminarPublicacionView: eliminarMiPublicacion()

EliminarPublicacionView -d-> PublicacionController: solicitarConfirmacion(id)
PublicacionController --> EliminarPublicacionView: presentarConfirmacion()
EliminarPublicacionView --> PublicacionController: confirmarEliminacion(id)
EliminarPublicacionView --> PublicacionController: cancelarEliminacion()
EliminarPublicacionView --> PublicacionController: validarEliminacion(id)
PublicacionController --> PublicacionRepository: obtenerPorId(id)
PublicacionController --> PublicacionRepository: eliminar(id)
PublicacionRepository -- Publicacion
EliminarPublicacionView ..> EstadoSalidaExitosa: publicacionEliminada()
EliminarPublicacionView ..> EstadoSalidaCancelada: eliminacionCancelada()


@enduml
