@startuml iniciarSesion-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":SESION_CERRADA" as EstadoEntrada
package iniciarSesion as "iniciarSesion()" {
    rectangle #629EF9 IniciarSesionView
    rectangle #b5bd68 SesionController
    rectangle #F2AC4E UsuarioRepository
    rectangle #F2AC4E Usuario
    rectangle #F2AC4E SesionRepository
    rectangle #F2AC4E Sesion
}

rectangle #CDEBA5 ":PANEL_PRINCIPAL_ABIERTO" as EstadoSalida


EstadoEntrada -r-> IniciarSesionView: iniciarSesion()

IniciarSesionView -d-> SesionController: iniciarSesion(credenciales)
SesionController --> UsuarioRepository: obtenerPorCorreo(correo)
SesionController --> Usuario: validarCredenciales(credenciales) : boolean
SesionController --> IniciarSesionView: presentarCredencialesIncorrectas() [credenciales incorrectas]
SesionController --> SesionRepository: registrarSesion(usuario) [credenciales correctas]
UsuarioRepository -- Usuario
SesionRepository -- Sesion
IniciarSesionView ..> EstadoSalida: presentarPanelPrincipal() [credenciales correctas]


@enduml
