@startuml abrirPublicaciones-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":PANEL_PRINCIPAL_ABIERTO" as EstadoEntrada1
rectangle #CDEBA5 ":PUBLICACION_ABIERTA" as EstadoEntrada2
package abrirPublicaciones as "abrirPublicaciones()" {
    rectangle #629EF9 ListarPublicacionesView
    rectangle #b5bd68 PublicacionController
    rectangle #F2AC4E PublicacionRepository
    rectangle #F2AC4E Publicacion
}

rectangle #CDEBA5 ":PUBLICACIONES_ABIERTAS" as EstadoSalida
rectangle #CDEBA5 ":Collaboration AbrirPublicacion" as AbrirPublicacion

EstadoEntrada1 -r-> ListarPublicacionesView: abrirPublicaciones()
EstadoEntrada2 -r-> ListarPublicacionesView: abrirPublicaciones(idPublicacion)

ListarPublicacionesView -d-> PublicacionController: listarPublicaciones(contexto)
ListarPublicacionesView --> PublicacionController: filtrarPublicaciones(criterio)
PublicacionController --> PublicacionRepository: obtenerPropios(investigador)
PublicacionController --> PublicacionRepository: obtenerPorContexto(contexto)
PublicacionController --> PublicacionRepository: buscarPorCriterio(criterio)
PublicacionRepository -- Publicacion
note right of PublicacionController
Contexto opcional:
- sin identificador: listado propio
- con identificador: listado propio acotado
end note
ListarPublicacionesView ..> EstadoSalida: continuarNavegacion()
ListarPublicacionesView ..> AbrirPublicacion: abrirPublicacion()

@enduml
