@startuml abrirPublicaciones-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":PANEL_PRINCIPAL_ABIERTO" as EstadoEntrada
package abrirPublicaciones as "abrirPublicaciones()" {
    rectangle #629EF9 ListarPublicacionesView
    rectangle #b5bd68 PublicacionController
    rectangle #F2AC4E PublicacionRepository
    rectangle #F2AC4E Publicacion
}

rectangle #CDEBA5 ":PUBLICACIONES_ABIERTAS" as EstadoSalida
rectangle #CDEBA5 ":Collaboration AbrirPublicacion" as AbrirPublicacion

EstadoEntrada -r-> ListarPublicacionesView: abrirPublicaciones()

ListarPublicacionesView -d-> PublicacionController: listarPublicaciones()
ListarPublicacionesView --> PublicacionController: filtrarPublicaciones(criterio)
PublicacionController --> PublicacionRepository: obtenerPropios(investigador)
PublicacionController --> PublicacionRepository: buscarPorCriterio(criterio)
PublicacionRepository -- Publicacion
ListarPublicacionesView ..> EstadoSalida: continuarNavegacion()
ListarPublicacionesView ..> AbrirPublicacion: abrirPublicacion()

@enduml
