@startuml abrirMiPublicacion-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":MIS_PUBLICACIONES_ABIERTAS" as EstadoEntrada
package abrirMiPublicacion as "abrirMiPublicacion()" {
    rectangle #629EF9 DetallePublicacionView
    rectangle #b5bd68 PublicacionController
    rectangle #F2AC4E PublicacionRepository
    rectangle #F2AC4E Publicacion
}

rectangle #CDEBA5 ":MI_PUBLICACION_ABIERTA" as EstadoSalida
rectangle #CDEBA5 ":Collaboration EditarPublicacion" as EditarPublicacion
rectangle #CDEBA5 ":Collaboration EliminarPublicacion" as EliminarPublicacion
rectangle #CDEBA5 ":Collaboration AbrirMisPublicaciones" as AbrirMisPublicaciones

EstadoEntrada -r-> DetallePublicacionView: abrirMiPublicacion()

DetallePublicacionView -d-> PublicacionController: obtenerPublicacion(id)
DetallePublicacionView --> PublicacionController: prepararAccionesDisponibles(coordinador)
PublicacionController --> PublicacionRepository: obtenerPorId(id)
PublicacionController --> PublicacionRepository: verificarPermisos(actor)
PublicacionRepository -- Publicacion
DetallePublicacionView ..> EstadoSalida: continuarNavegacion()
DetallePublicacionView ..> EditarPublicacion: editarPublicacion()
DetallePublicacionView ..> EliminarPublicacion: eliminarPublicacion()
DetallePublicacionView ..> AbrirMisPublicaciones: abrirMisPublicaciones()

@enduml
