@startuml solicitarEliminacionPerfil-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":OPCIONES_PERFIL_ABIERTO" as EstadoEntrada
package solicitarEliminacionPerfil as "solicitarEliminacionPerfil()" {
    rectangle #629EF9 SolicitarEliminacionPerfilView
    rectangle #b5bd68 PerfilController
    rectangle #F2AC4E PerfilRepository
    rectangle #F2AC4E Perfil
    rectangle #F2AC4E SolicitudEliminacionPerfilRepository
    rectangle #F2AC4E SolicitudEliminacionPerfil
}

rectangle #CDEBA5 ":SESION_CERRADA" as EstadoSalidaExitosa
rectangle #CDEBA5 ":OPCIONES_PERFIL_ABIERTO" as EstadoSalidaCancelada


EstadoEntrada -r-> SolicitarEliminacionPerfilView: solicitarEliminacionPerfil()

SolicitarEliminacionPerfilView -d-> PerfilController: solicitarEliminacionPerfil(datos)
SolicitarEliminacionPerfilView --> PerfilController: validarSolicitud(datos)
PerfilController --> PerfilRepository: existeSolicitudPendiente(perfil)
PerfilController --> SolicitudEliminacionPerfilRepository: guardar(solicitud)
PerfilRepository -- Perfil
SolicitudEliminacionPerfilRepository -- SolicitudEliminacionPerfil
SolicitarEliminacionPerfilView ..> EstadoSalidaExitosa: solicitudEnviada()
SolicitarEliminacionPerfilView ..> EstadoSalidaCancelada: cancelarSolicitud()


@enduml
