@startuml editarPublicacion-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":MI_PUBLICACION_ABIERTA" as EstadoEntrada
package editarPublicacion as "editarPublicacion()" {
    rectangle #629EF9 EditarPublicacionView
    rectangle #b5bd68 PublicacionController
    rectangle #F2AC4E PublicacionRepository
    rectangle #F2AC4E Publicacion
}

rectangle #CDEBA5 ":MI_PUBLICACION_ABIERTA" as EstadoSalida
rectangle #CDEBA5 ":Collaboration AbrirMisPublicaciones" as AbrirMisPublicaciones
rectangle #CDEBA5 ":Collaboration EliminarPublicacion" as EliminarPublicacion

EstadoEntrada -r-> EditarPublicacionView: editarPublicacion()

EditarPublicacionView -d-> PublicacionController: editarPublicacion(id, datos)
EditarPublicacionView --> PublicacionController: validarCambios(datos)
PublicacionController --> PublicacionRepository: obtenerPorId(id)
PublicacionController --> PublicacionRepository: actualizar(entidad)
PublicacionRepository -- Publicacion
EditarPublicacionView ..> EstadoSalida: continuarNavegacion()
EditarPublicacionView ..> AbrirMisPublicaciones: abrirMisPublicaciones()
EditarPublicacionView ..> EliminarPublicacion: eliminarPublicacion()

@enduml
