@startuml eliminarEntregable-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":ENTREGABLE_ABIERTO" as EstadoEntrada
package eliminarEntregable as "eliminarEntregable()" {
    rectangle #629EF9 EliminarEntregableView
    rectangle #b5bd68 EntregableController
    rectangle #F2AC4E EntregableRepository
    rectangle #F2AC4E Entregable
}

rectangle #CDEBA5 ":ENTREGABLES_ABIERTOS" as EstadoSalidaExitosa
rectangle #CDEBA5 ":ENTREGABLE_ABIERTO" as EstadoSalidaCancelada
rectangle #CDEBA5 ":Collaboration AbrirEntregable" as AbrirEntregable

EstadoEntrada -r-> EliminarEntregableView: eliminarEntregable()

EliminarEntregableView -d-> EntregableController: solicitarConfirmacion(id)
EntregableController --> EliminarEntregableView: presentarConfirmacion()
EliminarEntregableView --> EntregableController: confirmarEliminacion(id)
EliminarEntregableView --> EntregableController: cancelarEliminacion()
EliminarEntregableView --> EntregableController: validarEliminacion(id)
EntregableController --> EntregableRepository: obtenerPorId(id)
EntregableController --> EntregableRepository: eliminar(id)
EntregableRepository -- Entregable
EliminarEntregableView ..> EstadoSalidaExitosa: entregableEliminado()
EliminarEntregableView ..> EstadoSalidaCancelada: eliminacionCancelada()
EliminarEntregableView ..> AbrirEntregable: abrirEntregable()

@enduml
