@startuml cerrarSesion-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":PANEL_PRINCIPAL_ABIERTO" as EstadoEntrada
package cerrarSesion as "cerrarSesion()" {
    rectangle #629EF9 CerrarSesionView
    rectangle #b5bd68 SesionController
    rectangle #F2AC4E SesionRepository
    rectangle #F2AC4E Sesion
}

rectangle #CDEBA5 ":SESION_CERRADA" as EstadoSalida
rectangle #CDEBA5 ":PANEL_PRINCIPAL_ABIERTO" as EstadoCancelacion


EstadoEntrada -r-> CerrarSesionView: cerrarSesion()

CerrarSesionView --> CerrarSesionView: solicitarConfirmacion()
CerrarSesionView ..> EstadoCancelacion: cancelarCierre() [cancelacion]
CerrarSesionView -d-> SesionController: confirmarCierre() [confirmacion]
SesionController --> SesionRepository: obtenerSesionActiva(actor)
SesionController --> SesionRepository: cerrar(sesion)
SesionRepository -- Sesion
CerrarSesionView ..> EstadoSalida: presentarSesionCerrada()


@enduml
