@startuml abrirOpcionesPerfil-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":INVESTIGADOR_ABIERTO" as EstadoEntradaInvestigador
rectangle #CDEBA5 ":PANEL_PRINCIPAL_ABIERTO" as EstadoEntradaPanel
rectangle #CDEBA5 ":SOLICITUDES_ELIMINACION_PERFIL_ABIERTAS" as EstadoEntradaSolicitudes
package abrirOpcionesPerfil as "abrirOpcionesPerfil()" {
    rectangle #629EF9 OpcionesPerfilView
    rectangle #b5bd68 PerfilController
    rectangle #F2AC4E PerfilRepository
    rectangle #F2AC4E Perfil
}

rectangle #CDEBA5 ":OPCIONES_PERFIL_ABIERTO" as EstadoSalida
rectangle #CDEBA5 ":Collaboration EditarPerfil" as EditarPerfil
rectangle #CDEBA5 ":Collaboration SolicitarEliminacionPerfil" as SolicitarEliminacionPerfil
rectangle #CDEBA5 ":Collaboration AbrirPanelPrincipal" as AbrirPanelPrincipal
rectangle #CDEBA5 ":Collaboration AbrirInvestigador" as AbrirInvestigador
rectangle #CDEBA5 ":Collaboration AbrirSolicitudesEliminacionPerfil" as AbrirSolicitudesEliminacionPerfil

EstadoEntradaInvestigador -r-> OpcionesPerfilView: abrirOpcionesPerfil(id)
EstadoEntradaPanel -d-> OpcionesPerfilView: abrirOpcionesPerfil()
EstadoEntradaSolicitudes -d-> OpcionesPerfilView: abrirOpcionesPerfil()

OpcionesPerfilView -d-> PerfilController: obtenerPerfil(contexto)
OpcionesPerfilView --> PerfilController: prepararAccionesDisponibles(coordinador, contexto)
PerfilController --> PerfilRepository: obtenerPerfilPropioOInvestigador(contexto)
PerfilController --> PerfilRepository: verificarPermisos(actor)
PerfilRepository -- Perfil
OpcionesPerfilView ..> EstadoSalida: opcionesPerfilAbierto()
OpcionesPerfilView ..> EditarPerfil: editarPerfil()
OpcionesPerfilView ..> SolicitarEliminacionPerfil: solicitarEliminacionPerfil()
OpcionesPerfilView ..> AbrirPanelPrincipal: abrirPanelPrincipal()
OpcionesPerfilView ..> AbrirInvestigador: abrirInvestigador(id)
OpcionesPerfilView ..> AbrirSolicitudesEliminacionPerfil: abrirSolicitudesEliminacionPerfil()

@enduml
